import{a as v,S,i as p}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const $="https://pixabay.com/api/",E="44048245-ca045a99f6e49609e4580f957",O=15;async function g(e,r){const n={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:O},s=await v.get($,{params:n});if(s.status!==200)throw new Error(s.statusText);return s.data}let u;function P(e){return`<li class="card">
    <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
    </a>
    <div class="card-info">
        <p class="description"><b>Likes:</b> ${e.likes}</p>
        <p class="description"><b>Views:</b> ${e.views}</p>
        <p class="description"><b>Comments:</b> ${e.comments}</p>
        <p class="description"><b>Downloads:</b> ${e.downloads}</p>
    </div>
  </li>`}function R(e){return e.map(P).join("")}function x(){u?u.refresh():u=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function m(e){e.style.display="block"}function b(e){e.style.display="none"}function I(e){e.style.display="block"}function y(e){e.style.display="none"}function w(e){p.error({message:`An error occurred: ${e}. Please try again later.`,position:"topRight"})}function M(){p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}const h=document.querySelector(".form"),f=document.querySelector(".gallery"),c=document.querySelector("#loading"),i=document.querySelector("#load-more");let a="",l=1,L=0;y(i);h.addEventListener("submit",async e=>{if(e.preventDefault(),f.innerHTML="",a=e.target.request.value.trim(),l=1,!!a){m(c),y(i);try{const r=await g(a,l);L=r.totalHits,q(r)}catch(r){w(r.message)}finally{h.reset(),b(c)}}});i.addEventListener("click",async()=>{m(c),l+=1;try{const e=await g(a,l);q(e)}catch(e){w(e)}finally{b(c)}});function q(e){if(e.hits.length===0){p.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const r=R(e.hits);f.insertAdjacentHTML("beforeend",r),x();const{height:n}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"}),f.children.length<L?I(i):(y(i),M())}
//# sourceMappingURL=commonHelpers.js.map
